# Generated by Django 4.0 on 2021-12-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_commercial', models.BooleanField(default=False)),
                ('zip_code', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('complement', models.CharField(max_length=1028)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True)),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('uf_code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=256)),
                ('wireless_login', models.CharField(max_length=100)),
                ('wireless_password', models.CharField(max_length=100)),
                ('onu_login', models.CharField(max_length=100)),
                ('onu_password', models.CharField(max_length=100)),
                ('address_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_for', to='address.address')),
                ('address_instalation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalation_for', to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('ibge', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.state')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.city'),
        ),
    ]
