# Generated by Django 4.0 on 2021-12-21 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=256)),
                ('wireless_login', models.CharField(max_length=100)),
                ('wireless_password', models.CharField(max_length=100)),
                ('onu_login', models.CharField(max_length=100)),
                ('onu_password', models.CharField(max_length=100)),
                ('address_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_for', to='address.address')),
                ('address_instalation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalation_for', to='address.address')),
            ],
        ),
    ]
